#!/bin/bash

# This script copies the compiled plugin and installs it
# First you would have to run the following command to compile it 
# mvn clean package

###################################################################################
# YOU CAN CHANGE THESE VARIABLES TO MATCH YOUR USE CASE
###################################################################################

# Define where FLUME is installed
FLUME_HOME="/opt/flume"

# Plugin Current Version
JAMBALAYA_VERSION="0.8.0-SNAPSHOT"

###################################################################################
# DO NOT MODIFY THESE VARIABLES
###################################################################################

# This is the artifact that will be generated by Maven
MAIN_ARTIFACT="target/apache-flume-jambalaya-$JAMBALAYA_VERSION.jar"

# These are all the external dependencies used by this Plugin
EXTERNAL_LIBS="target/lib/*.jar"

# Folder where plugin will be installed
STAGING_FOLDER="/$FLUME_HOME/plugins.d/apache-flume-jambalaya"

# Folder containing plugin code
LIB_FOLDER="$STAGING_FOLDER/lib"

# Folder containing plugin dependencies (Java jars)
LIBEXT_FOLDER="$STAGING_FOLDER/libext"

# Folder containing plugin dependencies (C,C++ object files)
NATIVE_FOLDER="$STAGING_FOLDER/native"

# Get rid of the current plugin setup
rm -fR $STAGING_FOLDER

# Create the folder where the plugin will be installed
mkdir -p $LIB_FOLDER

# Create the folder where the plugin dependencies will be installed
mkdir -p $LIBEXT_FOLDER
mkdir -p $NATIVE_FOLDER

# Move over the plugin and its dependencies to their respective installation paths
cp -p $EXTERNAL_LIBS $LIBEXT_FOLDER
cp -p $MAIN_ARTIFACT $LIB_FOLDER


